# Site
name: "Fıçı Sertliği"
title: "Fıçı Sertliği | Brut De Fût"
description: "Simple Guide to Whisky"
logo: 'assets/images/logo.png'
favicon: 'favicon.ico'
google_analytics: 'UA-xxxxxxxx-1'
include: ["_pages"]
permalink: /:title/
email: ficisertligi@gmail.com
formspree_io_endpoint: https://formspree.io/f/mbjppjyr

# Authors
authors:
  emrah:
    name: Fıçı Sertliği
    display_name: Fıçı Sertliği
    email: ficisertligi@gmail.com
    instagram: https://instagram.com/brutdefut
    description: "ficisertligi.com yazarı"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: rouge
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]


url: https://brutdefut.github.io
baseurl: /ficisertligi
